plugins { id 'com.android.application' }

android {
    namespace 'com.haseltonmediagroup.newtonscradle3d'
    compileSdk 35

    defaultConfig {
        applicationId 'com.haseltonmediagroup.newtonscradle3d'
        minSdk 26
        targetSdk 35
        versionCode 10
        versionName '2.0.0-rebuild'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
